CMakeLists: Fix upstream RPATH pointing at source
The upstream commit below made the RPATH for liborbbec_camera.so point
to the directory _within_the_source_code_ where the binary blob .so's
are located!

This caused Yocto QA error:
ERROR: orbbec-camera-1.0-r0 do_package_qa: QA Issue: package orbbec-camera contains bad RPATH :/ldata/src/ros/yocto-commonk/tmp/work/skylake-64-oe-linux/orbbec-camera/1.0-r0/src/SDK/lib/x64
in file /ldata/src/ros/yocto-commonk/tmp/work/skylake-64-oe-linux/orbbec-camera/1.0-r0/packages-split/orbbec-camera/opt/ros/noetic/lib/liborbbec_camera.so [rpaths]

Fix this by removing the setting of the RPATH. Unfortunately, I do not
know what problem the author was trying to fix with that change to begin
with.

Fixes: 04a89f5b ("fixed cmake")